PREKEY_BATCH_SIZE = 100
MESSAGE_KEY_SEED_LENGTH = 32
CHAIN_KEY_LENGTH = 32
ROOT_KEY_LENGTH = 32

PRESENCE_CHANNEL = "presence"
MESSAGE_CHANNEL_PREFIX = "messages:"
TYPING_CHANNEL_PREFIX = "typing:"

REDIS_HOST = "localhost"
REDIS_PORT = 6380
REDIS_DB = 0